apiVersion: v1
kind: Service
metadata:
  name: pingdir-service
  labels:
    app: pingdir-service
spec:
  type: NodePort
  ports:
    - name: health
      protocol: TCP
      port: 1443
      nodePort: 31443
    - name: ldap
      protocol: TCP
      port: 1389
      nodePort: 31389
    - name: ldap2
      protocol: TCP
      port: 1636
      nodePort: 31637
    - name: ldaprep
      protocol: TCP
      port: 8989
      nodePort: 31089
  selector:
    app: pingdir-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingdir-deployment
  labels:
    app: pingdir-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingdir-deployment
  template:
    metadata:
      labels:
        app: pingdir-deployment
    spec:
      containers:
        - name: pingdirectory
          image: pingidentity/pingdirectory:2210-9.1.0.0
          volumeMounts:
            - name: hostvol
              mountPath: /opt/staging/pd.profile/server-root/pre-setup
          env:
            - name: LICENSE_FILE_NAME
              value: "PingDirectory-9.1-Production.lic"
            - name: SERVER_PROFILE_URL
              value: "https://github.com/pingidentity/pingidentity-server-profiles.git"
            - name: SERVER_PROFILE_PATH
              value: "getting-started/pingdirectory"
            - name: PING_IDENTITY_ACCEPT_EULA
              value: "YES"
      volumes:
        - name: hostvol
          hostPath:
            path: /Users/xcambou/Documents/work/xcambou-cloudsecds-k8s/src/main/resources/config/licdir
